# nightcrawler/config.py

# --- Core Configuration ---

# Limit the maximum number of concurrent background crawl/scan tasks
MAX_CONCURRENT_SCANS = 5

# User Agent string for requests generated by the script (crawler/scanner)
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# --- Additional Options (Examples) ---
# Path for an optional findings log file (if implemented)
# LOG_FILE_PATH = "scan_findings.log"

# Payloads for scans (could be defined here or imported)
SQLI_PAYLOADS = ["'", '"', "''", "' OR '1'='1", "' OR SLEEP(5)--"]
XSS_PAYLOADS = [
    "<script>alert('XSS1')</script>",
    "\"><script>alert('XSS2')</script>",
    "'\"/><svg/onload=alert('XSS3')>",
    "javascript:alert('XSS4')",
]
